version: '2'
services:
  wordpress:
    image: wordpress:5.2.2-php7.1
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_DB_NAME: wp_blocky
    ports:
      - 80:80
    networks:
      - shareddb_localnet
networks:
  shareddb_localnet:
    external: true  